version: '3.7'
services:
  server:
    image: python:3.8
    volumes:
      - ./app:/app  # Assuming your Flask app is in the 'app' folder in your project
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY_FILE=/app/generated_password.txt
    working_dir: /app
    command: python3 app.py  # Command to run the Flask app
    # Optionally, you can install dependencies using a Dockerfile or via entrypoint
